export enum AnalyticsMetric {
  // Funnel
  INTRO_FIRST_STEP_SEEN = 'INTRO_FIRST_STEP_SEEN',
  INTRO_FIRST_STEP_BUTTON_CLICKED = 'INTRO_FIRST_STEP_BUTTON_CLICKED',
  INTRO_SECOND_STEP_SEEN = 'INTRO_SECOND_STEP_SEEN',
  INTRO_SECOND_STEP_BUTTON_CLICKED = 'INTRO_SECOND_STEP_BUTTON_CLICKED',
  PHONE_NUMBER_SCREEN_SEEN = 'PHONE_NUMBER_SCREEN_SEEN',
  PHONE_NUMBER_SCREEN_BUTTON_CLICKED = 'PHONE_NUMBER_SCREEN_BUTTON_CLICKED',
  AUTH_SUCCESS = 'AUTH_SUCCESS',
  FIRST_TIME_CHATS_SCREEN_SEEN = 'FIRST_TIME_CHATS_SCREEN_SEEN',
  // Chats & analysis
  ANALYSIS_OPTIONS_SCREEN_SEEN = 'ANALYSIS_OPTIONS_SCREEN_SEEN',
  ANALYSIS_RESULT_SCREEN_SEEN = 'ANALYSIS_RESULT_SCREEN_SEEN',
  TELEGRAM_CHATS_SEEN = 'TELEGRAM_CHATS_SEEN',
  TELEGRAM_CHAT_SELECTED = 'TELEGRAM_CHAT_SELECTED',
  CHAT_ANALYSIS_STARTED = 'CHAT_ANALYSIS_STARTED',
  CHAT_ANALYSIS_OPTION_COMMUNICATION_CHARACTER_SELECTED = 'CHAT_ANALYSIS_OPTION_COMMUNICATION_CHARACTER_SELECTED',
  CHAT_ANALYSIS_OPTION_HOW_TO_COMMUNICATE_BETTER_SELECTED = 'CHAT_ANALYSIS_OPTION_HOW_TO_COMMUNICATE_BETTER_SELECTED',
  CHAT_ANALYSIS_OPTION_WHERE_AM_I_MAKING_MISTAKES_SELECTED = 'CHAT_ANALYSIS_OPTION_WHERE_AM_I_MAKING_MISTAKES_SELECTED',
  CHAT_ANALYSIS_OPTION_UNDERSTAND_THE_DYNAMIC_SELECTED = 'CHAT_ANALYSIS_OPTION_UNDERSTAND_THE_DYNAMIC_SELECTED',
  CHAT_ANALYSIS_OPTION_WHAT_TO_ANSWER_SELECTED = 'CHAT_ANALYSIS_OPTION_WHAT_TO_ANSWER_SELECTED',
  CHAT_ANALYSIS_REANALYZED = 'CHAT_ANALYSIS_REANALYZED',
  CHAT_ANALYSIS_COMPLETED = 'CHAT_ANALYSIS_COMPLETED',
}

const OPTION_TO_METRIC: Partial<Record<string, AnalyticsMetric>> = {
  communication_character: AnalyticsMetric.CHAT_ANALYSIS_OPTION_COMMUNICATION_CHARACTER_SELECTED,
  how_to_communicate_better: AnalyticsMetric.CHAT_ANALYSIS_OPTION_HOW_TO_COMMUNICATE_BETTER_SELECTED,
  where_am_i_making_mistakes: AnalyticsMetric.CHAT_ANALYSIS_OPTION_WHERE_AM_I_MAKING_MISTAKES_SELECTED,
  understand_the_dynamic: AnalyticsMetric.CHAT_ANALYSIS_OPTION_UNDERSTAND_THE_DYNAMIC_SELECTED,
  what_to_answer: AnalyticsMetric.CHAT_ANALYSIS_OPTION_WHAT_TO_ANSWER_SELECTED,
};

export function getOptionMetric(questionType: string): AnalyticsMetric | null {
  return OPTION_TO_METRIC[questionType] ?? null;
}
